name: Run Apex Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-apex-tests:
    strategy:
      matrix:
        sf_org_alias: [STAGEFULL]

    env:
      ENVIRONMENT: ${{ matrix.sf_org_alias }}

    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Populate auth file with SFDX_URL secret of org
        run: echo "${{ secrets[format('SFDX_{0}_URL', env.ENVIRONMENT)] }}" > SFDX_${{ matrix.sf_org_alias }}_URL.txt

      - name: Authenticate Target Org
        run: sf org login sfdx-url -f SFDX_${{ matrix.sf_org_alias }}_URL.txt -s

      - name: Run apex tests and store test run Id
        run: |
          output=$(sf apex run test --json)
          test_id=$(echo "$output" | jq -r '.result.testRunId') 
          echo "$test_id" > ${{ matrix.sf_org_alias }}_test_run_id.txt

      - name: Upload the test run Id as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.sf_org_alias }}_test_run_id
          path: ${{ matrix.sf_org_alias }}_test_run_id.txt
